env:
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_SHELL: "false"
  PLUGIN_DOCKER_COMPOSE_VERSION: "4621e87e1a2bc348acfda29dd569144bd4220adc"

steps:
  - label: ":ruby: Tests"
    command: rspec
    plugins:
      - ecr#v2.1.1:
          login: true
          region: "us-east-1"

      - https://github.com/outstand/docker-compose-buildkite-plugin.git#${PLUGIN_DOCKER_COMPOSE_VERSION}:
          run: server
          propagate-uid-gid: true
